language: csharp

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update -qq
  - sudo apt-get install -qq gtk-sharp2

before_script:
  - pwd
  - mkdir ../build/
  # SolidOpt
  - mkdir ../build/SolidOptBuild/
  # SolidV
  - mkdir ../build/SolidVBuild
  # SolidReflector
  - mkdir ../build/SolidReflectorBuild
  # DataMorphose
  - mkdir ../build/DataMorphoseBuild
  # SampleTool
  - mkdir ../build/SampleToolBuild
  # SilidIDE
  - mkdir ../build/SolidIDEBuild

script:
  - cd ../build/SolidOptBuild/
  - pwd
  - ../../solid/SolidOpt/configure
  - travis_retry make -j4 -k
  - ctest --output-on-failure #-j4
  - cd ../SolidVBuild/
  - pwd
  - ../../solid/SolidV/configure
  - travis_retry make -j4 -k
  - cd ../SolidReflectorBuild/
  - pwd
  - ../../solid/Tools/SolidReflector/configure
  - travis_retry make -j4 -k
  - cd ../DataMorphoseBuild/
  - pwd
  - ../../solid/Tools/DataMorphose/configure
  - travis_retry make -j4 -k
  - ctest --output-on-failure #-j4
  - cd ../SampleToolBuild
  - pwd
  - ../../solid/Tools/SampleTool/configure
  - travis_retry make -j4 -k
  - cd ../SolidIDEBuild
  - pwd
  - ../../solid/Tools/SolidIDE/configure
#  - travis_retry make -j4 -k
  - travis_retry make -k

branches:
  only:
    - master

# Notify developers when build passed/failed.
notifications:
  recipients:
    - solid-commits@solidopt.org
    - vvasilev@cern.ch
  email:
    on_success: change
    on_failure: always
  #irc:
    #channels:
    #- "chat.freenode.net#rubinius"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
